use std::{
   collections::HashSet,
   fmt::Write as _,
};

use crate::{
   config::Config,
   utils::html_escape,
   types::{
      List,
      Tweet,
      Tweets,
      User,
   },
   utils::formatters,
   views::renderutils::community_note_to_html,
};

/// Snowflake ID cutoff for RSS GUID format transition. Corresponds to
/// approximately December 14, 2025 UTC.
const GUID_CUTOFF: i64 = 2_000_000_000_000_000_000;

/// Build a complete RSS feed from channel metadata and pre-rendered items.
fn rss_channel(
   self_url: &str,
   title: &str,
   link: &str,
   description: &str,
   image_block: &str,
   items: &str,
) -> String {
   format!(
      r#"<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
  <channel>
    <atom:link href="{self_url}" rel="self" type="application/rss+xml" />
    <title>{title}</title>
    <link>{link}</link>
    <description>{}</description>
    <language>en-us</language>
    <ttl>40</ttl>
{image_block}{items}  </channel>
</rss>"#,
      escape_xml(description),
   )
}

/// Render an RSS feed for a user's timeline with optional pinned tweet.
#[expect(
   clippy::module_name_repetitions,
   reason = "public API name is clear and conventional"
)]
pub fn render_user_rss(user: &User, tweets: &Tweets, config: &Config, feed_kind: &str) -> String {
   render_user_rss_with_pinned(user, tweets, config, feed_kind, None)
}

/// Render an RSS feed for a user's timeline with pinned tweet support.
pub fn render_user_rss_with_pinned(
   user: &User,
   tweets: &Tweets,
   config: &Config,
   feed_kind: &str,
   pinned: Option<&Tweet>,
) -> String {
   let url_prefix = config.url_prefix();
   let feed_path = match feed_kind {
      "replies" => format!("/{}/with_replies/rss", user.username),
      "media" => format!("/{}/media/rss", user.username),
      _ => format!("/{}/rss", user.username),
   };

   let handle = format!("@{}", user.username);
   let title = escape_xml(&format!("{} / {handle}", user.fullname)).replace('\n', " ");
   let description = format!("Twitter feed for: {handle}. Generated by {url_prefix}");
   let link = format!("{url_prefix}/{}", user.username);
   let avatar = get_pic_url(&user.user_pic, config);
   let image_block = format!(
      "    <image>\n      <title>{title}</title>\n      <link>{link}</link>\n      \
       <url>{url_prefix}{avatar}</url>\n      <width>128</width>\n      <height>128</height>\n    \
       </image>\n"
   );

   let items = render_tweet_items_with_pinned(tweets, config, pinned, Some(&user.id));
   rss_channel(
      &format!("{url_prefix}{feed_path}"),
      &title,
      &link,
      &description,
      &image_block,
      &items,
   )
}

/// Render an RSS feed for search results.
#[expect(
   clippy::module_name_repetitions,
   reason = "public API name is clear and conventional"
)]
pub fn render_search_rss(query: &str, tweets: &Tweets, config: &Config) -> String {
   let url_prefix = config.url_prefix();
   let esc_name = escape_xml(query);
   let items = render_tweet_items(tweets, config);
   let description = format!("Twitter feed for: Search \"{esc_name}\". Generated by {url_prefix}");
   rss_channel(
      &format!("{url_prefix}/search"),
      &format!("Search results for \"{esc_name}\""),
      &format!("{url_prefix}/search"),
      &description,
      "",
      &items,
   )
}

/// Render an RSS feed for a Twitter list.
#[expect(
   clippy::module_name_repetitions,
   reason = "public API name is clear and conventional"
)]
pub fn render_list_rss(list: &List, tweets: &Tweets, config: &Config) -> String {
   let url_prefix = config.url_prefix();
   let link = format!("{url_prefix}/i/lists/{}", list.id);
   let items = render_tweet_items(tweets, config);
   let title = format!("{} / @{}", escape_xml(&list.name), list.username);
   let description = format!(
      "Twitter feed for: {} by @{}. Generated by {url_prefix}",
      list.name, list.username
   );
   rss_channel(&link, &title, &link, &description, "", &items)
}

/// Render tweet items for RSS feed.
fn render_tweet_items(tweets: &Tweets, config: &Config) -> String {
   render_tweet_items_with_pinned(tweets, config, None, None)
}

/// Render tweet items with optional pinned tweet at top and `userId` filtering.
fn render_tweet_items_with_pinned(
   tweets: &Tweets,
   config: &Config,
   pinned: Option<&Tweet>,
   user_id: Option<&str>,
) -> String {
   let url_prefix = config.url_prefix();
   let pinned_id = pinned.map(|tweet| tweet.id);
   let mut seen_links: HashSet<String> = HashSet::new();

   let mut items = Vec::new();

   // Add pinned tweet first if present
   if let Some(pinned_tweet) = pinned {
      let link = get_link(pinned_tweet);
      if seen_links.insert(link) {
         items.push(render_tweet_item(pinned_tweet, url_prefix, config));
      }
   }

   // Add regular tweets, skipping pinned if already added and filtering by userId
   for tweet in tweets {
      if Some(tweet.id) == pinned_id {
         continue;
      }
      // Filter by userId for user timeline feeds
      if user_id.is_some_and(|uid| tweet.user.id != uid) {
         continue;
      }
      let link = get_link(tweet.retweet.as_deref().unwrap_or(tweet));
      // Deduplicate by link
      if !seen_links.insert(link) {
         continue;
      }
      items.push(render_tweet_item(tweet, url_prefix, config));
   }

   items.join("")
}

/// Get the link path for a tweet.
fn get_link(tweet: &Tweet) -> String {
   super::renderutils::tweet_link(tweet)
}

/// Build title: "Pinned:", "RT by @user:", "R to @user:", then text.
fn get_title(tweet: &Tweet, retweet_username: &str) -> String {
   let mut prefix = String::new();
   if tweet.pinned {
      prefix.push_str("Pinned: ");
   } else if !retweet_username.is_empty() {
      let _ = write!(prefix, "RT by @{retweet_username}: ");
   } else if !tweet.reply.is_empty() {
      let _ = write!(prefix, "R to @{}: ", tweet.reply[0]);
   }

   let text = strip_html(&tweet.text);
   if !text.is_empty() {
      return format!("{}{}", prefix, escape_xml(&text));
   }

   // Fallback to media type
   if !tweet.photos.is_empty() {
      return format!("{prefix}Image");
   }
   if tweet.video.is_some() {
      return format!("{prefix}Video");
   }
   if tweet.gif.is_some() {
      return format!("{prefix}Gif");
   }

   prefix
}

/// Render the body of a single tweet for RSS.
fn render_rss_tweet(tweet: &Tweet, config: &Config) -> String {
   let url_prefix = config.url_prefix();

   // Use replaceUrls with absolute URLs
   let text = formatters::replace_urls_abs(&tweet.text, config, url_prefix);
   let mut body = format!("<p>{}</p>", text.replace('\n', "<br>\n"));

   // Photos
   if !tweet.photos.is_empty() {
      for photo in &tweet.photos {
         let pic_url = get_pic_url(&photo.url, config);
         let _ = write!(
            body,
            r#"<img src="{url_prefix}{pic_url}" style="max-width:250px;" />"#
         );
      }
   } else if let Some(ref video) = tweet.video {
      // Video: linked thumbnail with "Video" label
      if !video.thumb.is_empty() {
         let thumb_url = get_pic_url(&video.thumb, config);
         let tweet_link = format!("{}{}", url_prefix, get_link(tweet));
         let _ = write!(
            body,
            r#"<a href="{tweet_link}">
<br>Video<br>
  <img src="{url_prefix}{thumb_url}" style="max-width:250px;" />
</a>"#
         );
      }
   } else if let Some(ref gif) = tweet.gif {
      // GIF: <video> element
      let thumb = format!("{}{}", url_prefix, get_pic_url(&gif.thumb, config));
      let url = format!("{}{}", url_prefix, get_pic_url(&gif.url, config));
      let _ = write!(
         body,
         r#"<video poster="{thumb}" autoplay muted loop style="max-width:250px;">
  <source src="{url}" type="video/mp4"></video>"#
      );
   } else if let Some(ref card) = tweet.card {
      // Card image
      if !card.image.is_empty() {
         let card_url = get_pic_url(&card.image, config);
         let _ = write!(
            body,
            r#"<img src="{url_prefix}{card_url}" style="max-width:250px;" />"#
         );
      }
   }

   // Community note
   if let Some(ref note) = tweet.note {
      let note_html = community_note_to_html(note);
      let note_text = formatters::replace_urls_abs(&note_html, config, url_prefix);
      let _ = write!(body, "<p><b>Community note:</b> {note_text}</p>");
   }

   // Quote tweet
   if let Some(ref quote) = tweet.quote
      && quote.available
   {
      let quote_link = format!("{}{}", url_prefix, get_link(quote));
      let quote_body = render_rss_tweet(quote, config);
      let _ = write!(
         body,
         r#"<hr/>
<blockquote>
<b>{} (@{})</b>
<p>
{quote_body}
</p>
<footer>
— <cite><a href="{quote_link}">{quote_link}</a>
</footer>
</blockquote>"#,
         quote.user.fullname, quote.user.username
      );
   }

   body
}

/// Render a single tweet as an RSS item.
fn render_tweet_item(tweet: &Tweet, url_prefix: &str, config: &Config) -> String {
   // Handle retweets: extract inner tweet
   let retweet_username = if tweet.retweet.is_some() {
      tweet.user.username.as_str()
   } else {
      ""
   };
   let display_tweet = tweet.retweet.as_ref().map_or(tweet, |rt| rt.as_ref());

   let pub_date = display_tweet
      .time
      .map(formatters::format_rfc822_time)
      .unwrap_or_default();

   let link = format!("{url_prefix}{}", get_link(display_tweet));
   let title = formatters::sanitize_xml(&get_title(display_tweet, retweet_username));
   let description = formatters::sanitize_xml(&render_rss_tweet(display_tweet, config));

   // GUID: use bare tweet ID for new tweets (>= cutoff), URL for old
   let guid = if display_tweet.id >= GUID_CUTOFF {
      format!(
         r#"        <guid isPermaLink="false">{}</guid>"#,
         display_tweet.id
      )
   } else {
      format!("        <guid>{link}</guid>")
   };

   format!(
      "      <item>
        <title>{title}</title>
        <dc:creator>@{}</dc:creator>
        <description><![CDATA[{}]]></description>
        <pubDate>{pub_date}</pubDate>
{guid}
        <link>{link}</link>
      </item>
",
      display_tweet.user.username,
      description.trim(),
   )
}

/// Helper to get proxied pic URL path (not full URL).
fn get_pic_url(url: &str, config: &Config) -> String {
   formatters::get_pic_url(url, config.config.base64_media)
}

/// Strip HTML tags from text (for titles).
fn strip_html(text: &str) -> String {
   let mut result = String::new();
   let mut in_tag = false;
   for ch in text.chars() {
      if ch == '<' {
         in_tag = true;
      } else if ch == '>' {
         in_tag = false;
      } else if !in_tag {
         result.push(ch);
      }
   }
   result
}

/// Escape XML special characters (delegates to shared `html_escape`).
fn escape_xml(input: &str) -> String {
   html_escape(input).into_owned()
}
